package global

import (
	"regexp"
	"siploadbalancer/cl"
	"siploadbalancer/prometheus"
	"sync"
)

const (
	BUE               string = "SipLoadBalancer/v1.0"
	BufferSize        int    = 4096
	DeltaRune         rune   = 'a' - 'A'
	MultipartBoundary string = "unique-boundary-1"
)

var (
	SipUdpPort  int
	HttpTcpPort int
	RateLimit   int

	Prometrics *prometheus.Metrics

	WtGrp      sync.WaitGroup
	BufferPool *sync.Pool = NewSyncPool()

	CallLimiter *cl.CallLimiter
)

var (
	methods      = [...]string{"UNKNOWN", "INVITE", "INVITE", "REFER", "ACK", "CANCEL", "BYE", "OPTIONS", "NOTIFY", "UPDATE", "PRACK", "INFO", "REGISTER", "SUBSCRIBE", "MESSAGE", "PUBLISH", "NEGOTIATE"}
	directions   = [...]string{"INBOUND", "OUTBOUND"}
	messageTypes = [...]string{"INVALID", "REQUEST", "RESPONSE"}
)

var (
	DicBodyContentType = map[BodyType]string{
		SDP:                  "application/sdp",
		DTMF:                 "application/dtmf",
		DTMFRelay:            "application/dtmf-relay",
		MultipartMixed:       "multipart/mixed",
		MultipartAlternative: "multipart/alternative",
		MultipartRelated:     "multipart/related",
		ISUP:                 "application/isup",
		QSIG:                 "application/qsig",
		SIPFragment:          "message/sipfrag",
		SimpleMsgSummary:     "application/simple-message-summary",
		PlainText:            "text/plain",
		PIDFXML:              "application/pidf+xml",
		MSCPXML:              "application/mscp+xml",
		MSCXML:               "application/mediaservercontrol+xml",
		ResourceListXML:      "application/resource-lists+xml",
		VndEtsiPstnXML:       "application/vnd.etsi.pstn+xml",
		VndOrangeInData:      "application/vnd.orange.indata",
		AppJson:              "application/json",
		AnyXML:               "+xml",
	}

	DicFieldRegEx = map[FieldPattern]*regexp.Regexp{
		RAckHeader:                 regexp.MustCompile(`(?i)^(\d+)\s+(\d+)\s+INVITE\s*$`),
		NumberOnly:                 regexp.MustCompile(`(?i)(?:sip|sips|tel):([\*\#\+]?[\d\.\-]+|Invalid|Anonymous|Unavailable)@?`),
		NameAndNumber:              regexp.MustCompile(`(?i)("?[^<"]+?"?)?\s*<(?:sip|tel):([\*\#\+]?[\d\.\-]+|Invalid|Anonymous|Unavailable)@?`),
		ReplaceNumberOnly:          regexp.MustCompile(`(?i)(.*?(?:sip|sips|tel):)(?:[\*\#\+]?[\d\.\-]+|Invalid|Anonymous|Unavailable)(.*)`),
		RequestStartLinePattern:    regexp.MustCompile(`(?i)^\s*([a-z]+)\s+((?:\w+):(?:(?:[^@]+)@)?(?:[^@]+))\s+(SIP/2\.0)$`),
		INVITERURI:                 regexp.MustCompile(`(?i)^([a-z]+):([\*\#\+]?[a-f0-9\.\-]+)((?:[,;](?:[\w\-]+|[\w\-]+=[^@=,;]+))*)@([^\*\#\+@:,;]+(?::(?:\d+))?)((?:[,;](?:[\w\-]+|[\w\-]+=[^@=,;]+))*)$`),
		ResponseStartLinePattern:   regexp.MustCompile(`(?i)^\s*(SIP/2\.0)\s+(\d{3})(?:\s+([^,;]+)([,;].+)?)?$`),
		ViaBranchPattern:           regexp.MustCompile(`(?i);branch\s*=\s*([^;,]+)`),
		ViaTransport:               regexp.MustCompile(`(?i)SIP/2.0/(\w+)`),
		MediaPayloadTypes:          regexp.MustCompile(`(?i)^m=\w+\s+(\d+)\s+([^\s]+)\s+([\w\s]+)`),
		MediaPayloadTypeDefinition: regexp.MustCompile(`(?i)a=(?:rtpmap|fmtp)\s*:\s*(\d+)\s+`),
		SDPOriginLine:              regexp.MustCompile(`(?i)^o=[^\s]+\s+(\d+)\s+(\d+)\s+IN\s+IP4\s+((?:\d{1,3}\.){3}\d{1,3})`),
		MediaDirective:             regexp.MustCompile(`(?i)^a=(sendrecv|sendonly|recvonly|inactive)\s*$`),
		ConnectionAddress:          regexp.MustCompile(`(?i)^c=IN\s+IP4\s+((?:\d{1,3}\.){3}\d{1,3})`),
		FullHeader:                 regexp.MustCompile(`(?i)^\s*([^:]+)\s*:\s*(.+)$`),
		MediaLine:                  regexp.MustCompile(`(?i)^m=(\w+)\s+(?:\d+)\s+`),
		HostIPPort:                 regexp.MustCompile(`(?i)(?:sip|sips|tel):(?:[^@]+@)?((?:\d{1,3}\.){3}\d{1,3}):(\d+);?`),
		FQDNPort:                   regexp.MustCompile(`(?i)(?:sip|sips|tel):(?:[^@]+@)?([\w\-\.]+)(?::(\d+))?;?`),
		TransportProtocol:          regexp.MustCompile(`(?i)transport\s*=\s*(\w+)`),
		ViaIPv4Socket:              regexp.MustCompile(`(?i)\s*SIP/2\.0\/(\w+)\s+((?:\d{1,3}\.){3}\d{1,3})(:\d+)?\s*`),
		IP6:                        regexp.MustCompile(`(?i)((?:(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){6})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:::(?:(?:(?:[0-9a-f]{1,4})):){5})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){4})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,1}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){3})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,2}(?:(?:[0-9a-f]{1,4})))?::(?:(?:(?:[0-9a-f]{1,4})):){2})(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,3}(?:(?:[0-9a-f]{1,4})))?::(?:(?:[0-9a-f]{1,4})):)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,4}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:(?:(?:(?:[0-9a-f]{1,4})):(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9]))\.){3}(?:(?:25[0-5]|(?:[1-9]|1[0-9]|2[0-4])?[0-9])))))))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,5}(?:(?:[0-9a-f]{1,4})))?::)(?:(?:[0-9a-f]{1,4})))|(?:(?:(?:(?:(?:(?:[0-9a-f]{1,4})):){0,6}(?:(?:[0-9a-f]{1,4})))?::)))))\s*$`),
		IP4:                        regexp.MustCompile(`(?i)((?:(?:2(?:5[0-5]|[0-4]\d)|1?\d?\d)\.){3}(?:2(?:5[0-5]|[0-4]\d)|1?\d?\d))\s*$`),
		HeaderParameter:            regexp.MustCompile(`(?i);([^=]+)=([^=;]+)`),
		SDPTime:                    regexp.MustCompile(`(?i)^t=(.+)`),
		Header:                     regexp.MustCompile(`(?i)^(?:[a-z]+-)*[a-z]+$`),
		URIFull:                    regexp.MustCompile(`(?i)((?:sip|sips|tel):[^>]+)`),
		URIParameters:              regexp.MustCompile(`(?i)^(?:[,;](?:[\w\-]+|[\w\-]+=[^@=,;]+))*$`),
		HTTPRequestStartLine:       regexp.MustCompile(`(?i)^([a-z]+)\s+((?:/[^\s/]*)+)\s+HTTP/1.1`),
		URIParameter:               regexp.MustCompile(`(?i)^([^=]+)=([^=]+)$`),
		CSeqHeader:                 regexp.MustCompile(`(?i)(\d+)\s+([a-z]+)`),
		HandlingProfile:            regexp.MustCompile(`(?i)\[([a-z0-9_\-]+)\]`),
		ErrorStack:                 regexp.MustCompile(`(?i)(\w+\.vb):line\s(\d+)`),
		SDPALineReMapping:          regexp.MustCompile(`(?i)^(a=\w+\s*:\s*)(?:\d+)(.+)`),
		SDPPTDefinition:            regexp.MustCompile(`(?i)^a=rtpmap\s*:\s*\d+\s(.+)`),
		CodecPolicy:                regexp.MustCompile(`(?i)(([0-9]|[1-9][0-9]|1[01][0-9]|12[0-7])|\*)`),
		ObjectName:                 regexp.MustCompile(`(?i)^\[.+?\]$`),
		SignalDTMF:                 regexp.MustCompile(`(?i)^\s*(Signal)\s*=\s*([^\r\n]+)$`),
		DurationDTMF:               regexp.MustCompile(`(?i)^\s*(Duration)\s*=\s*([^\r\n]+)$`),
		ConfDropPart:               regexp.MustCompile(`(?i)^88(\d{1,2})[\*#]$`),
		Tag:                        regexp.MustCompile(`(?i);tag=([^;]+)`),
	}

	HeaderStringtoEnum = map[string]HeaderEnum{
		"Accept":                        Accept,
		"Accept-Contact":                Accept_Contact,
		"Accept-Encoding":               Accept_Encoding,
		"Accept-Language":               Accept_Language,
		"Accept-Resource-Priority":      Accept_Resource_Priority,
		"Alert-Info":                    Alert_Info,
		"Allow":                         Allow,
		"Allow-Events":                  Allow_Events,
		"Answer-Mode":                   Answer_Mode,
		"Authentication-Info":           Authentication_Info,
		"Authorization":                 Authorization,
		"Call-ID":                       Call_ID,
		"Call-Info":                     Call_Info,
		"Compression":                   Compression,
		"Contact":                       Contact,
		"Content-Disposition":           Content_Disposition,
		"Content-Encoding":              Content_Encoding,
		"Content-Language":              Content_Language,
		"Content-Length":                Content_Length,
		"Content-Type":                  Content_Type,
		"Cisco-Guid":                    Cisco_Guid,
		"CSeq":                          CSeq,
		"Custom-CLI":                    Custom_CLI,
		"Date":                          Date,
		"Diversion":                     Diversion,
		"Error-Info":                    Error_Info,
		"Event":                         Event,
		"Expires":                       Expires,
		"Feature-Caps":                  Feature_Caps,
		"Flow-Timer":                    Flow_Timer,
		"From":                          From,
		"Geolocation":                   Geolocation,
		"Geolocation-Error":             Geolocation_Error,
		"Geolocation-Routing":           Geolocation_Routing,
		"History-Info":                  History_Info,
		"Identity":                      Identity,
		"Identity-Info":                 Identity_Info,
		"In-Reply-To":                   In_Reply_To,
		"Info-Package":                  Info_Package,
		"Join":                          Join,
		"Max-Breadth":                   Max_Breadth,
		"Max-Expires":                   Max_Expires,
		"Max-Forwards":                  Max_Forwards,
		"MIME-Version":                  MIME_Version,
		"Min-Expires":                   Min_Expires,
		"Min-SE":                        Min_SE,
		"Organization":                  Organization,
		"P-Access-Network-Info":         P_Access_Network_Info,
		"P-Answer-State":                P_Answer_State,
		"P-Asserted-Identity":           P_Asserted_Identity,
		"P-Asserted-Service":            P_Asserted_Service,
		"P-Associated-URI":              P_Associated_URI,
		"P-Called-Party-ID":             P_Called_Party_ID,
		"P-Charging-Function-Addresses": P_Charging_Function_Addresses,
		"P-Charging-Vector":             P_Charging_Vector,
		"P-DCS-Billing-Info":            P_DCS_Billing_Info,
		"P-DCS-LAES":                    P_DCS_LAES,
		"P-DCS-OSPS":                    P_DCS_OSPS,
		"P-DCS-Redirect":                P_DCS_Redirect,
		"P-DCS-Trace-Party-ID":          P_DCS_Trace_Party_ID,
		"P-Early-Media":                 P_Early_Media,
		"P-Media-Authorization":         P_Media_Authorization,
		"P-Preferred-Identity":          P_Preferred_Identity,
		"P-Preferred-Service":           P_Preferred_Service,
		"P-Private-Network-Indication":  P_Private_Network_Indication,
		"P-Profile-Key":                 P_Profile_Key,
		"P-Refused-URI-List":            P_Refused_URI_List,
		"P-Served-User":                 P_Served_User,
		"P-User-Database":               P_User_Database,
		"P-Visited-Network-ID":          P_Visited_Network_ID,
		"Path":                          Path,
		"Permission-Missing":            Permission_Missing,
		"Policy-Contact":                Policy_Contact,
		"Policy-ID":                     Policy_ID,
		"Priority":                      Priority,
		"Priv-Answer-Mode":              Priv_Answer_Mode,
		"Privacy":                       Privacy,
		"Proxy-Authenticate":            Proxy_Authenticate,
		"Proxy-Authorization":           Proxy_Authorization,
		"Proxy-Require":                 Proxy_Require,
		"RAck":                          RAck,
		"Reason":                        Reason,
		"Reason-Phrase":                 Reason_Phrase,
		"Record-Route":                  Record_Route,
		"Recv-Info":                     Recv_Info,
		"Refer-Events-At":               Refer_Events_At,
		"Refer-Sub":                     Refer_Sub,
		"Refer-To":                      Refer_To,
		"Referred-By":                   Referred_By,
		"Reject-Contact":                Reject_Contact,
		"Replaces":                      Replaces,
		"Reply-To":                      Reply_To,
		"Request-Disposition":           Request_Disposition,
		"Require":                       Require,
		"Resource-Priority":             Resource_Priority,
		"Retry-After":                   Retry_After,
		"Route":                         Route,
		"RSeq":                          RSeq,
		"Security-Client":               Security_Client,
		"Security-Server":               Security_Server,
		"Security-Verify":               Security_Verify,
		"Server":                        Server,
		"Service-Route":                 Service_Route,
		"Session-Expires":               Session_Expires,
		"Session-ID":                    Session_ID,
		"SIP-ETag":                      SIP_ETag,
		"SIP-If-Match":                  SIP_If_Match,
		"Subject":                       Subject,
		"Subscription-State":            Subscription_State,
		"Subscription-Expires":          Subscription_Expires,
		"Supported":                     Supported,
		"Suppress-If-Match":             Suppress_If_Match,
		"Target-Dialog":                 Target_Dialog,
		"Timestamp":                     Timestamp,
		"To":                            To,
		"Trigger-Consent":               Trigger_Consent,
		"Unsupported":                   Unsupported,
		"User-Agent":                    User_Agent,
		"User-to-User":                  User_to_User,
		"Via":                           Via,
		"Warning":                       Warning,
		"WWW-Authenticate":              WWW_Authenticate,
	}

	HeaderEnumToString = map[HeaderEnum]string{
		Accept:                        "Accept",
		Accept_Contact:                "Accept-Contact",
		Accept_Encoding:               "Accept-Encoding",
		Accept_Language:               "Accept-Language",
		Accept_Resource_Priority:      "Accept-Resource-Priority",
		Alert_Info:                    "Alert-Info",
		Allow:                         "Allow",
		Allow_Events:                  "Allow-Events",
		Answer_Mode:                   "Answer-Mode",
		Authentication_Info:           "Authentication-Info",
		Authorization:                 "Authorization",
		Call_ID:                       "Call-ID",
		Call_Info:                     "Call-Info",
		Compression:                   "Compression",
		Contact:                       "Contact",
		Content_Disposition:           "Content-Disposition",
		Content_Encoding:              "Content-Encoding",
		Content_Language:              "Content-Language",
		Content_Length:                "Content-Length",
		Content_Type:                  "Content-Type",
		Cisco_Guid:                    "Cisco-Guid",
		CSeq:                          "CSeq",
		Custom_CLI:                    "Custom-CLI",
		Date:                          "Date",
		Diversion:                     "Diversion",
		Error_Info:                    "Error-Info",
		Event:                         "Event",
		Expires:                       "Expires",
		Feature_Caps:                  "Feature-Caps",
		Flow_Timer:                    "Flow-Timer",
		From:                          "From",
		Geolocation:                   "Geolocation",
		Geolocation_Error:             "Geolocation-Error",
		Geolocation_Routing:           "Geolocation-Routing",
		History_Info:                  "History-Info",
		Identity:                      "Identity",
		Identity_Info:                 "Identity-Info",
		In_Reply_To:                   "In-Reply-To",
		Info_Package:                  "Info-Package",
		Join:                          "Join",
		Max_Breadth:                   "Max-Breadth",
		Max_Expires:                   "Max-Expires",
		Max_Forwards:                  "Max-Forwards",
		MIME_Version:                  "MIME-Version",
		Min_Expires:                   "Min-Expires",
		Min_SE:                        "Min-SE",
		Organization:                  "Organization",
		P_Access_Network_Info:         "P-Access-Network-Info",
		P_Answer_State:                "P-Answer-State",
		P_Asserted_Identity:           "P-Asserted-Identity",
		P_Asserted_Service:            "P-Asserted-Service",
		P_Associated_URI:              "P-Associated-URI",
		P_Called_Party_ID:             "P-Called-Party-ID",
		P_Charging_Function_Addresses: "P-Charging-Function-Addresses",
		P_Charging_Vector:             "P-Charging-Vector",
		P_DCS_Billing_Info:            "P-DCS-Billing-Info",
		P_DCS_LAES:                    "P-DCS-LAES",
		P_DCS_OSPS:                    "P-DCS-OSPS",
		P_DCS_Redirect:                "P-DCS-Redirect",
		P_DCS_Trace_Party_ID:          "P-DCS-Trace-Party-ID",
		P_Early_Media:                 "P-Early-Media",
		P_Media_Authorization:         "P-Media-Authorization",
		P_Preferred_Identity:          "P-Preferred-Identity",
		P_Preferred_Service:           "P-Preferred-Service",
		P_Private_Network_Indication:  "P-Private-Network-Indication",
		P_Profile_Key:                 "P-Profile-Key",
		P_Refused_URI_List:            "P-Refused-URI-List",
		P_Served_User:                 "P-Served-User",
		P_User_Database:               "P-User-Database",
		P_Visited_Network_ID:          "P-Visited-Network-ID",
		Path:                          "Path",
		Permission_Missing:            "Permission-Missing",
		Policy_Contact:                "Policy-Contact",
		Policy_ID:                     "Policy-ID",
		Priority:                      "Priority",
		Priv_Answer_Mode:              "Priv-Answer-Mode",
		Privacy:                       "Privacy",
		Proxy_Authenticate:            "Proxy-Authenticate",
		Proxy_Authorization:           "Proxy-Authorization",
		Proxy_Require:                 "Proxy-Require",
		RAck:                          "RAck",
		Reason:                        "Reason",
		Reason_Phrase:                 "Reason-Phrase",
		Record_Route:                  "Record-Route",
		Recv_Info:                     "Recv-Info",
		Refer_Events_At:               "Refer-Events-At",
		Refer_Sub:                     "Refer-Sub",
		Refer_To:                      "Refer-To",
		Referred_By:                   "Referred-By",
		Reject_Contact:                "Reject-Contact",
		Replaces:                      "Replaces",
		Reply_To:                      "Reply-To",
		Request_Disposition:           "Request-Disposition",
		Require:                       "Require",
		Resource_Priority:             "Resource-Priority",
		Retry_After:                   "Retry-After",
		Route:                         "Route",
		RSeq:                          "RSeq",
		Security_Client:               "Security-Client",
		Security_Server:               "Security-Server",
		Security_Verify:               "Security-Verify",
		Server:                        "Server",
		Service_Route:                 "Service-Route",
		Session_Expires:               "Session-Expires",
		Session_ID:                    "Session-ID",
		SIP_ETag:                      "SIP-ETag",
		SIP_If_Match:                  "SIP-If-Match",
		Subject:                       "Subject",
		Subscription_State:            "Subscription-State",
		Subscription_Expires:          "Subscription-Expires",
		Supported:                     "Supported",
		Suppress_If_Match:             "Suppress-If-Match",
		Target_Dialog:                 "Target-Dialog",
		Timestamp:                     "Timestamp",
		To:                            "To",
		Trigger_Consent:               "Trigger-Consent",
		Unsupported:                   "Unsupported",
		User_Agent:                    "User-Agent",
		User_to_User:                  "User-to-User",
		Via:                           "Via",
		Warning:                       "Warning",
		WWW_Authenticate:              "WWW-Authenticate",
	}
)

func NewSyncPool() *sync.Pool {
	return &sync.Pool{
		New: func() any {
			b := make([]byte, BufferSize)
			return &b
		},
	}
}
